/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * SPlayer MPRIS 主类
 * 暴露给 Node.js 的接口，用于管理 MPRIS 服务器和播放器状态
 */
export declare class SPlayerMpris {
  /** 构造函数：创建 MPRIS 服务器并在 D-Bus 上注册 */
  constructor()
  /**
   * 注册事件处理回调函数
   * 当系统通过 MPRIS 控制播放器时，会调用此回调
   *
   * # TypeScript 签名
   * ```typescript
   * registerEventHandler(callback: (event: MprisEvent) => void): void
   * ```
   */
  registerEventHandler(callback: (event: MprisEvent) => void): void
  /**
   * 设置播放状态
   * 更新内部状态并通过 D-Bus 通知系统（会更新系统媒体控制面板）
   *
   * # 参数
   * * `status` - "Playing" / "Paused" / "Stopped"
   */
  setPlaybackStatus(status: string): void
  /**
   * 设置音轨元数据
   * 更新歌曲信息（标题、艺术家、专辑、时长、封面）并通知系统
   *
   * # 参数
   * * `info` - 包含音轨信息的结构体
   */
  setMetadata(info: TrackInfo): void
  /**
   * 设置播放位置
   * 更新当前播放位置并发送 Seeked 信号
   *
   * # 参数
   * * `pos` - 位置（微秒）
   */
  setPosition(pos: number): void
  /**
   * 设置音量
   *
   * # 参数
   * * `volume` - 音量值 (0.0 ~ 1.0)
   */
  setVolume(volume: number): void
  /** 获取循环模式 */
  getLoopStatus(): string
  /**
   * 设置循环模式
   *
   * # 参数
   * * `status` - "Track" (单曲循环) / "Playlist" (列表循环) / "None" (不循环)
   */
  setLoopStatus(status: string): void
  /** 获取随机播放状态 */
  getShuffle(): boolean
  /**
   * 设置随机播放
   *
   * # 参数
   * * `shuffle` - 是否启用随机播放
   */
  setShuffle(shuffle: boolean): void
  /**
   * 设置播放进度
   * 同时更新位置和时长信息
   *
   * # 参数
   * * `pos` - 当前位置（微秒）
   * * `length` - 总时长（微秒），大于 0 时会更新元数据中的时长
   */
  setProgress(pos: number, length: number): void
}

/** MPRIS 事件结构体 */
export interface MprisEvent {
  /** 事件类型: "play", "pause", "next", "previous", "seek", "set_position" 等 */
  eventType: string
  /** 可选的数值参数，例如 seek 时的偏移量（毫秒） */
  value?: number
}

/**
 * 音轨信息结构体
 * 从 JS 传入，用于更新 MPRIS 元数据（在系统通知栏/媒体控制面板显示）
 */
export interface TrackInfo {
  /** 歌曲标题 */
  title?: string
  /** 艺术家名称 */
  artist?: string
  /** 专辑名称 */
  album?: string
  /** 歌曲长度（毫秒），从 JS 传入 */
  length?: number
  /** 封面图片 URL */
  url?: string
}
