/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 关闭 Discord RPC */
export declare function disableDiscordRpc(): void

/**
 * 禁用媒体控件
 *
 * ### Errors
 *
 * 会在调用 API 失败时抛出错误
 */
export declare function disableSystemMedia(): void

/** Discord 配置参数 */
export interface DiscordConfigPayload {
  /**
   * 暂停时是否显示
   *
   * 注意暂停时进度会固定为 0
   */
  showWhenPaused: boolean
  /** 显示模式，参考 [`DiscordDisplayMode`] */
  displayMode?: DiscordDisplayMode
}

/**
 * Discord 显示模式枚举
 *
 * 不打开详细信息面板时，在用户名下方显示的小字
 */
export type DiscordDisplayMode = /** Listening to SPlayer */
'Name'|
/** Listening to Rick Astley */
'State'|
/** Listening to Never Gonna Give You Up */
'Details';

/**
 * 启用 Discord RPC
 *
 * ### 备注
 *
 * 启用后会立刻尝试连接，如果 Discord 未启动，或因为其他未知原因连接失败，会每 5 秒尝试连接一次
 */
export declare function enableDiscordRpc(): void

/**
 * 启用媒体控件
 *
 * ### Errors
 *
 * 会在调用 API 失败时抛出错误
 */
export declare function enableSystemMedia(): void

/**
 * 初始化插件
 *
 * ### 参数
 *
 * * `log_dir` - 要把日志文件保存到的路径
 *
 * ### Errors
 *
 * 可能会在日志初始化失败，或者媒体控件初始化失败时抛出错误
 *
 * ### 备注
 *
 * 如果其他 API 调用失败，则只会打印日志并静默失败
 */
export declare function initialize(logDir: string): void

export interface MetadataParam {
  songName: string
  authorName: string
  albumName: string
  /** 封面的原始字节数据，适用于除 Discord RPC 之外的其他平台 */
  coverData?: Buffer
  /**
   * 封面的 HTTP URL，更新 Discord RPC 时必传，其他平台可不传
   *
   * Linux 平台在没有提供 `cover_data` 时会使用它
   */
  originalCoverUrl?: string
  /**
   * 网易云音乐中对应的曲目 ID
   *
   * ### 用途
   * - 以 "NCM-{ID}" 的格式上传到 SMTC 的 “流派” 字段
   * - 生成 Discord RPC 的按钮链接
   * - MacOS 和 Linux 会使用此值来填充唯一的曲目 ID
   */
  ncmId?: number
  /**
   * 当前歌曲时长，单位是毫秒
   *
   * 用于 Linux、MacOS、Discord RPC 的元数据更新。Windows 使用 [`TimelinePayload`] 的
   * `total_time` 字段。
   */
  duration?: number
}

export type PlaybackStatus =  'Playing'|
'Paused';

export interface PlayModePayload {
  isShuffling: boolean
  repeatMode: RepeatMode
}

export interface PlayStatePayload {
  status: PlaybackStatus
}

/**
 * 注册媒体控件的事件回调 (上一首、下一首、暂停、播放等)
 *
 * ### 参数
 *
 * `(event: SystemMediaEvent) => void`
 *
 * ### Errors
 *
 * 如果 N-API 创建线程安全函数失败，会抛出错误。通常不应该发生，除非 JS 环境已经销毁了
 */
export declare function registerEventHandler(callback: (arg: SystemMediaEvent) => void): void

export type RepeatMode =  'None'|
'Track'|
'List';

/** 关闭插件，清理资源 */
export declare function shutdown(): void

export interface SystemMediaEvent {
  type: SystemMediaEventType
  positionMs?: number
  rate?: number
}

export type SystemMediaEventType =  'Play'|
'Pause'|
'Stop'|
'NextSong'|
'PreviousSong'|
'ToggleShuffle'|
'ToggleRepeat'|
'SetRate'|
/** 绝对位置，毫秒 */
'Seek';

export interface TimelinePayload {
  /** 单位是毫秒 */
  currentTime: number
  /** 单位是毫秒 */
  totalTime: number
  /** 是否为 seek 操作触发的更新 */
  seeked?: boolean
}

/**
 * 更新 Discord RPC 的配置
 *
 * ### 参数
 *
 * * `payload` - 配置信息，可以配置是否在暂停后也显示 Discord Activity 和 状态显示风格。详情请查看
 *   [`DiscordConfigPayload`]
 */
export declare function updateDiscordConfig(payload: DiscordConfigPayload): void

/**
 * 更新歌曲元数据
 *
 * 同时也会更新 Discord 的元数据 (如果启用了 Discord RPC)
 *
 * ### 备注
 *
 * 更新 Discord RPC 的元数据时，必须提供 `original_cover_url`
 */
export declare function updateMetadata(payload: MetadataParam): void

/**
 * 更新播放速率
 *
 * ### 备注
 *
 * 只会更新媒体控件的信息，不会更新 Discord RPC 上的信息
 */
export declare function updatePlaybackRate(rate: number): void

/**
 * 更新播放模式
 *
 * ### 备注
 *
 * 只会更新媒体控件的信息，不会更新 Discord RPC 上的信息
 */
export declare function updatePlayMode(payload: PlayModePayload): void

/**
 * 更新播放状态 (播放/暂停)
 *
 * 同时也会更新 Discord 的播放状态 (如果启用了 Discord RPC)
 */
export declare function updatePlayState(payload: PlayStatePayload): void

/**
 * 更新进度信息
 *
 * 同时也会更新 Discord 的进度信息 (如果启用了 Discord RPC)
 *
 * ### 备注
 *
 * Discord RPC 实现的进度更新有节流，调用此函数无需担心 Discord RPC 的速率限制
 */
export declare function updateTimeline(payload: TimelinePayload): void
