/* auto-generated by NAPI-RS */

export declare class DownloadTask {
  constructor();
  cancel(): void;
  download(
    url: string,
    filePath: string,
    metadata: SongMetadata | undefined | null,
    threadCount: number,
    referer: string | undefined | null,
    onProgress: (err: Error | null, arg: DownloadProgress) => any,
    enableHttp2: boolean,
  ): Promise<void>;
}

export interface DownloadProgress {
  percent: number;
  transferredBytes: number;
  totalBytes: number;
}

export declare function getTaskbarCreatedMessageId(): number;

export interface MusicTrack {
  id: string
  path: string
  title: string
  artist: string
  album: string
  duration: number
  cover?: string
  mtime: number
  size: number
  bitrate: number
  trackNumber?: number
}

export interface ScanEvent {
  event: string;
  tracks?: Array<MusicTrack>;
  progress?: ScanProgress;
  deletedPaths?: Array<string>;
}

export declare function scanMusicLibrary(
  dbPath: string,
  musicDirs: Array<string>,
  coverDir: string,
  callback: (err: Error | null, arg: ScanEvent) => any,
): Promise<void>;

export interface ScanProgress {
  current: number;
  total: number;
}

export interface SongMetadata {
  title: string;
  artist: string;
  album: string;
  coverUrl?: string;
  lyric?: string;
  description?: string;
  albumArtist?: string;
  genre?: string;
  year?: number;
  trackNumber?: number;
  discNumber?: number;
}

export declare function writeMusicMetadata(
  filePath: string,
  metadata: SongMetadata,
  coverPath?: string | undefined | null,
): Promise<void>;
